language: node_js
node_js:
- '7'
script:
- npm test
- yarn build
- scripts/travis-build
sudo: false
addons:
  apt:
    packages:
    - lftp
os: linux
deploy:
  provider: heroku
  api_key:
    secure: "095e5640-c329-427c-b5ef-c7baa7e04f61"
env:
  global:
  - secure: fiO/uDstcXJiHMVH5HGFzZKBQcex+c16Ng2QUDiiey3UHK3vrft2bSREkTWyBClUWTGamwCnPzNHTvbfd08zLWoDw6+2lTo/iCNR71OjKREnZoUYSoB+ZM5N/VQdSrAM7VbBA3JBS2+DXnzXYo4QSNX3twx88vukyRt7WgmVOl6KFmmhqbrAtzdfdyNd3EetEWTwy9doAxo5tc5lM+3/KPOEKp6d0oiVbOP1MW01B8qAnf4cl5mCnCtDDFOpF0VZ7hOabvQ/4T1Btya/L8hbMxUOrVToR2b24r/LUa3/8uNl+N5aB/Ky3ajC7lfmV5w04rct1Ac8bl9cu1ujRc0KBz/bYNdMuerdHoKYbW70bJ91p6HgO88hwP2RFTH0y3IqQoV+eZMU49qE3ycwBYcnL1aO7gnoE5Ql1CHxkCOYDhxu0yEGssrco6yGxndPiKpkFrpzwlAhI4xmfWx8piVKFEJ2nS2HJlUjI4DQ15hDI2DJiLRMugLXUk5reqZGj5KiL2g7O/YAG21mOJodYjn5mIxXoQh6wYMxB3nJtcJ1ZAmSNoJok7GEHGVZsPwNrv14TVIIx+VaJJ2JBQngoWggfDZXkp4U0DbepaSeQAkWmve0QyK+eHS519855iaz6+mOixHPEyJC7YmPcOFHg+KrC0iHeB7CMb6gas7uOahzmJA=
  - secure: JuHP9C+CLgROSgye+wY26E5PoezxVHQ+GnOc/xoOjp/vGceY6h7AyBUkvpE99kKHMjoAyDD/gOLmtygbfz4lKIpL6FV83HNBpKScvFgS1hdVdz+G7ziVyoqkHHdF1i+6OuzTCewUSmjx1y2Vve+Zh9RImZljlB6aOjvQwjUq2IQWSwZY2AUJfkJVvyv8JjcRajDB4BNu5nmLNod4aCWm8AQk5A/sK/iqu8/X1PfC5y93CoMuj49JCQMb5i5N+aj9qY8dGsPnBDqEX8SLHZXxx7SXXYbTF0BSwr0ioUNXkAOzz7b9er392CkzeYRflVRR1+8FHksrnTEG2ROEbOlTaXNhnINdO4EbFOOhMKqwaYASO0qXk0mdPi6XucHMFqGzwt5rKC3t16XN5Lv3erzSWJFQLQbBLrhbFHRY7MkvOTcCXbfqqFW6vlttcAp6X59Kwley3WUvkKUmhA2IOqga2QMI6y10lLlkaSUTu4SHtXHWDaeBNzdzfTJXDZjQ8wbhOsnGCLbQeDhXDZ4zBE8JgvWe0XmBgKlipNvlCScGH1/A9aKZZe+PoYfRdH+4rFniYEsL+3mv5x7eg6ij2LULQNwcDOaxNJQLUBhxg4HnkUJjaQ0g10lCMjpVvvgvx31s9If3XTxb2QdSWPTq3cTKhW+MI2Ue7v1yqgz4pd9o9mM=
  - secure: g5tv38YrQCb3Cp42cwKavYQS1LUryonZ6Bsem8IqZSxtdhB2mTq1LXmwnEvWrL/IsKWvBfLWm6WypqYJX1utuAd5Z/1qSVfO6rwBj810TU/oJcnyX0UeE12wamHHQ67128995o+NjSF5YTff06wDEia4gUjSYgTilvNQG6grIz/dWch9UKfaLRjL7M/srrquJWHI9tcgPPw9g6T3vvF+sppoNJAZfcPy0ssASLuM4rI884IexrmRR5JWD0bWFPm3IjVBVR+kgoh8+99gmLejQ43MQzkN/a8Jba2CZ0LLSGtVF7I9qt4tbPC+oqqTzSCRLNjZ2S7Ok1T31tm5pd4jrdSZ4QVZIbYFitkxFIzNxZbI9fAdK1ncE2JeyTcmxuSsoxWaazfF64Acv2WP/W7Ztt04OYI/G3cdZkb96aFchtSiB4dD1ZIQTlY6MWZx0GH5ATzkmvk2G6aKc0/oHjPxRHdeH5D2fM3ij9hRsXZnxJMxMwm+imZpjVLUWs1mULXFvFHo2OijkgXXI1KXIRqYBXYaQ9m/GroAjI48HRhXoxx2JVRe9bnIjskvsrQ1rRveeuVVj7KKXIxkdSh5PJpq1Z9WhhgQoI93ukWZIblq6G2HWKgOUIYNqQunTndk7PRUTYM/Uz0aperUfw+/OnXjVhNcqSrKS0xebtbk4XxXI20=
